// Generated by Selenium IDE
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Parameters;
import org.testng.annotations.Optional;
import org.testng.annotations.Test;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class GoogleMapsNavigation {

    private WebDriver driver;

    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeTest
    public void setUp() {

        //System.setProperty("webdriver.chrome.driver", "/Users/alans/tools/chromedriver");
        System.setProperty("webdriver.gecko.driver", "/Users/alans/tools/geckodriver");

        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);

    }
    @AfterTest
    public void tearDown() {
        driver.quit();
    }
    @Test
    @Parameters ({"startingPoint", "destination"})
    public void startingPointToDestination(@Optional ("New York City, New York") String startingPoint,
                                         @Optional ("Los Angeles, California") String destination) {


        driver.get("https://www.google.com/maps");
        driver.manage().window().setSize(new Dimension(1024, 800));
        driver.findElement(By.id("searchboxinput")).sendKeys(destination);
        driver.findElement(By.id("searchboxinput")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector(".iRxY3GoUYUY__promoted .iRxY3GoUYUY__button")).click();
        driver.findElement(By.cssSelector("#sb_ifc51 > .tactile-searchbox-input")).sendKeys(startingPoint);
        driver.findElement(By.cssSelector("#sb_ifc51 > .tactile-searchbox-input")).sendKeys(Keys.ENTER);
        driver.findElement(By.cssSelector("#section-directions-trip-title-0 > span")).click();

    }
}

